title: Bragadeesh Jegannathan
url: 'http://bragboy.com'

# Enable one of these styles by removing #
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: Bragadeesh Jegannathan
tagline: Entrepreneur
pic: braga.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: bragboy@gmail.com
website: tech.bragboy.com
linkedin: jbragadeesh
github: bragboy
twitter: '@bragabrags'