title: Bragadeesh Jegannathan
url: 'http://bragboy.com'

style: styles

#Profile information
name: Bragadeesh Jegannathan
tagline: Enterprise Architect
pic: braga.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: bragboy@gmail.com
website: tech.bragboy.com
linkedin: jbragadeesh
github: bragboy
twitter: '@bragabrags'